# Generated by Django 5.2.8 on 2025-11-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, to='students.course'),
        ),
    ]
