# Generated by Django 5.2.8 on 2025-11-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentprofile_is_active_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_active',
        ),
    ]
