# Generated by Django 5.2.8 on 2025-11-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_studentprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
